### PR TITLE
refactor: Docker

### PR DESCRIPTION
**Pull request by S0ly**
I'm currently addressing issue #938, though it's still a work in progress. (do not merge for the moment)

The current code incorporates two Docker configurations: one for development and another for deployment, catering to Unraid users.

I've organized these configurations into two folders:

Development: This folder houses the original Docker setup tailored for development purposes.

Standalone: Here, you'll find a modified Docker setup focused solely on running the CtrlPanel with an integrated Nginx. This streamlined setup requires only an external database and Pterodactyl to function efficiently.

I plan to include comprehensive documentation for the standalone setup to ensure ease of use and understanding.

- [x] make standalone docker
- [x] remake development docker
- [x] add better documentation
- [x] add GitHub workflow for update automation

known issue :
- account creation blocked by IP may be bugged because of the docker

### CODE REVIEW

**Comment by MrWeez** [comment]
You can mark the PR as a draft.

**Comment by S0ly** [comment]
So Like said in the original PR t might be worth considering issue #944. Although related to documentation, the changes proposed there don't directly impact the Docker configurations. However, as suggested in the issue, cleaning up the documentation and merging the building.md markdown into a readme in the development folder could streamline the user experience. This way, users will have everything conveniently located in one place.

**Comment by S0ly** [comment]
I'm not sure that the start and stop Docker scripts in the bin folder are still needed since Docker Compose already does it automatically ?

**Comment by 1day2die** [comment]
> I'm not sure that the start and stop Docker scripts in the bin folder are still needed since Docker Compose already does it automatically ?

noone really knows as we never really worked on it anyway

**Comment by S0ly** [comment]
@1day2die so I can delete what I think is not useful anymore and even modify the documentations for dockers ? so that I can make you a working development docker and standalone ?

**Comment by S0ly** [comment]
image

while testing the standalone docker I found that ti could be nice to detect that the panel is in a docker and desactivate things like the mysql and git detection :)

**Comment by 1day2die** [comment]
> @1day2die so I can delete what I think is not useful anymore and even modify the documentations for dockers ? so that I can make you a working development docker and standalone ?

yes

**Comment by S0ly** [comment]
I think the standalone docker is ready, I just need you @1day2die to test it by going to `/docker/standalone` and doing `docker compose up` it should make the docker, then you will be able to have it on your `http://localhost/install`

if yes its that I succeeded and so you can make an official docker image, I will then try to publish it to platform like unraid 
and I will also update the main readme documentation for it but I think I will need another PR for that

**Comment by S0ly** [comment]
for more clarification for these two commit
I was asking myself why this docker was present he was strange, and seing who made it, the commit is named "development docker" so I was right it was not made to be user by user

I used a lot of part of this development docker to make the standalone, so I updated it now, 
the development docker use the standalone and add more tools like Mysql, redis, php my admin, via a docker compose
and I plan to add things like pterodactyl and wings so that in 1 command you can have a full setup working

**Comment by S0ly** [comment]
The docker is finished, documentation could be upgraded but will be done in the futur
it needs testing it currently works but need testing for wen 0.10 will be finished to be sure everything is working
so do not merge if not tested on RC of 0.10

**Comment by S0ly** [comment]
@IceToast can you check and merge it please ? some documentation is not done and testing is not done too but for doc there is #969 and for test #928

this PR is just waiting here :)

**Comment by S0ly** [comment]
I mean... its like 4 month that we are running it in a docker on our side but it have not been tested by many people only us and james

**Pull request merged**
