### PR TITLE
fix: Conflict Resolution, Merge Main to Development

### PR DESCRIPTION
**Pull request by S0ly**
This PR aims to resolve all conflicts between the main and dev branches by merging all beneficial changes from main into dev. This ensures no features are lost when dev is released as main.

**Warning:** Only experienced contributors should handle this, as careful conflict resolution is crucial.

Thank you !

### CODE REVIEW

**Comment by S0ly** [comment]
any news on this ?

**Comment by 1day2die** [comment]
we will do this when dev is ready

**Comment by 1day2die** [comment]
actually, looking at this i have no fucking clue whats going on.
Cant we just force the dev branch into main once release-ready?

**Comment by S0ly** [comment]
this is a very bad idea but you do what you want lol

**Comment by S0ly** [comment]
next time never push to main instread of dev lol

**Comment by S0ly** [comment]
no one wants to make it so I guess we will blindly erase the main branch

**Comment by AGuyNamedJens** [comment]
I mean.. why merge if dev branch has a lot of new features :D

**Pull request closed without merging**
