### PR TITLE
[Feature] Update and Refactor the Github and Doc

### PR DESCRIPTION
**Pull request by S0ly**
I'm currently addressing issue #944, though it's still a work in progress. (do not merge for the moment)

Changes:
- Added an empty code of conduct in the .github directory.
- Moved the contributing.md file to the .github directory.
- Moved building.md into a readme file next to the relevant Docker.

Feel free to review and provide updates to this branch. Thanks!

### CODE REVIEW

**Comment by S0ly** [comment]
many of the files that I add are empty

the main readme of the project need to be modified, and the issue template and code of conduct need to be filled

**Comment by S0ly** [comment]
many file are visibly not used but still here, 

like at the root :
test.json (mentioned nowhere in the code)
composer (empty file) (mentioned nowhere in the code)

or in the bin :
test.sh (mentioned nowhere in the code)

**Comment by 1day2die** [comment]
> many file are visibly not used but still here,
> 
> like at the root : test.json (mentioned nowhere in the code) composer (empty file) (mentioned nowhere in the code)
> 
> or in the bin : test.sh (mentioned nowhere in the code)
> 
> should I delete them ?

can be deleted if empty

**Comment by S0ly** [comment]
sometimes they are not empty but just not used by the code

**Comment by S0ly** [comment]
I've made significant updates to the GitHub, including thorough doc cleaning. However, for the changes to take full effect, we'll need 1Day2Die to update the GitHub configuration.

This pull request introduces a more user-friendly and informative main readme, aimed at guiding users effectively. Additionally, I've added new documents for contribution guidelines, a code of conduct, pull request template, and security policy and moved them all to .github folder.

Moreover, I've cleaned up unused files and fixed broken links, and documented the .gitignore, .gitatribute, and .env.example files for clarity.

While these changes represent a solid starting point for a clearer and updated GitHub presence, there may be further adjustments needed in the future.

**Comment by 1day2die** [comment]
LGTM, Ready to merge?

**Comment by S0ly** [comment]
Yes if Everything is good for you :)

**Pull request merged**
