### PR TITLE
Move transferusers

### PR DESCRIPTION
**Pull request by jameskitt616**
Move transferusers file for #952 also Updated docs see: https://github.com/Ctrlpanel-gg/docs/pull/117

### CODE REVIEW

**Comment by IceToast** [comment]
It is not part of the App (which is the laravel app) imo. Actually the transfer users script should ultimately not exist and be a laravel command (app/kernel/commands)

**Comment by jameskitt616** [comment]
So delete the script and only rely on this? https://market.ctrlpanel.gg/resources/resource/35-transfer-users-from-ptero-to-cpgg/

**Comment by IceToast** [comment]
Both options are not ideal

**Comment by jameskitt616** [comment]
I do agree, a laravel command would make the most sense. No clue how to write one tho.

**Comment by jameskitt616** [comment]
So what happens next? Do i close the PR and trash it? & Remove the Docs PR.

**Comment by S0ly** [comment]
@IceToast

**Comment by IceToast** [comment]
I would not move it. I would keep it as is (a temporary solution) that gets replaced with a laravel command later on

**Pull request closed without merging**
