### PR TITLE
feat: Add readable name to permissions

### PR DESCRIPTION
**Pull request by Ferks-FK**
Add friendly names for role permissions.

This needs a refactoring of the way permissions are checked on controllers.

### CODE REVIEW

**Comment by S0ly** [comment]
is this still up to date ?

**Comment by S0ly** [comment]
I cant resolve the conflict and I cant determine the priority of this feature

**Comment by 1day2die** [comment]
> I cant resolve the conflict and I cant determine the priority of this feature

its a huge step for user friendliness

**Comment by S0ly** [comment]
so its a medium or high priority ?

**Comment by 1day2die** [comment]
should be resolved?

**Comment by 1day2die** [comment]
not tested at all

**Comment by 1day2die** [comment]
> so its a medium or high priority ?

medium

**Comment by S0ly** [comment]
and what need to be done for it to be merged ?

**Comment by 1day2die** [comment]
@Ferks-FK

**Comment by S0ly** [comment]
ferk told me on discord that he didnt remembered :(

**Comment by Ferks-FK** [comment]
> and what need to be done for it to be merged ?

I think my original plan was to use laravel Policies on the controller side

**Comment by S0ly** [comment]
so what we do if this PR ? @Ferks-FK will you finish it ? what is it used for because the description is very vague

**Comment by Ferks-FK** [comment]
> so what we do of this PR ? @Ferks-FK will you finish it ? what is it used for because the description is very vague

It can be merged as it is (needs testing), taking into account that the development branch needs to be tested as a whole.

**Comment by S0ly** [comment]
@Ferks-FK im confused by the files, can you more explain what is going on what are the change and what they do ? 
and deactivate the draft more of the PR if you think it can be merged thanks !

**Comment by S0ly** [comment]
any news ?

**Comment by Ferks-FK** [comment]
> @Ferks-FK im confused by the files, can you more explain what is going on what are the change and what they do ? and deactivate the draft mode of the PR if you think it can be merged thanks !

I commented that this would need a refactoring in the way permissions are checked in the backend, but this can easily be done in another PR, because it would take a lot of changes.
So I'll open this PR, and it could be merged.

**Comment by S0ly** [comment]
okay @IceToast need you :)

**Review by IceToast — APPROVED** [review]

**Comment by S0ly** [comment]
why you don't merge it ? :)

**Comment by IceToast** [comment]
This PR has conflicts with development. @Ferks-FK can you fix them in order to merge the PR?

**Pull request merged**
