### PR TITLE
Upgrading the panel to laravel version 11

### PR DESCRIPTION
**Pull request by Zastinian**
In this pr the code is updated to be compatible with laravel 11

I tested the dependencies and everything that is updated and left it working, if there is any error you can let me know, the current errors are the same of the normal development version.

### CODE REVIEW

**Comment by S0ly** [comment]
he is cooking xD

**Comment by Zastinian** [comment]
If someone can fix the problem by using use Spatie\Permission\PermissionRegistrar; to re-add it instead of using the default or else I add config.

I am currently looking at that.

https://spatie.be/docs/laravel-permission/v6/upgrading#content-upgrading-from-v5-to-v6

Error: Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotPermission

config('permission.column_names.role_pivot_key') ?: 'role_id';
config('permission.column_names.permission_pivot_key') ?: 'permission_id';

**Comment by Zastinian** [comment]
I already re-implemented the PermissionRegistrar class, you should find everything alright.

**Comment by 1day2die** [comment]
is this guy FR? haha damn

**Comment by 1day2die** [comment]
LGTM, please merge the latest development branch into this PR to fix the latest installer errors like Redis and GetEnv.. THen its ready to merge

**Pull request merged**
