### PR TITLE
If discord is connected, use discord avatar instead of gravatar

### PR DESCRIPTION
**Pull request by 1day2die**
https://github.com/ControlPanel-gg/dashboard/pull/226

### CODE REVIEW

**Comment by anondev-sudo** [comment]
It's not working, I still see gravatar default avatars when viewing users in admin area.
Also users see their gravatars.
image

**Comment by j122j** [comment]
This was removed in https://github.com/ControlPanel-gg/dashboard/commit/deb4e897014102b9eb7ef19d801ad27ca70972ee

**Comment by anondev-sudo** [comment]
Oh, should be added back

**Comment by 1day2die** [comment]
no. it increased loading times by a lot. you can grab the code from here and use in your panel though

https://github.com/ControlPanel-gg/dashboard/pull/226/files

**Comment by SneakyHub** [comment]
You can literally cache the discord avatars when the dashboard syncs statistics and use the cached avatars instead of live avatars that way loading times are basically the same,

**Comment by IceToast** [comment]
Exactly thats meant with "other ways" :D in the mentioned issue

**Pull request merged**
