### PR TITLE
fix: Panel Inconsistencies and issues

### PR DESCRIPTION
**Pull request by S0ly**
This branch focuses on resolving critical issues to prepare for production deployment. Below is the list of issues that need to be addressed:

- [x] csrf forms miss the hidden input and cause a 419 error
- [x] #933
- [x] #888 
- [x] #886 
- [x] #935 
- [x] #954 
- [x] #988
- [x] #989
- [x] #960 (fix roles) 
- [x] #958 
- [x] #971 
- [x] #970 
- [x] #1011
- [x] #1013

If you discover additional issues, please inform me, and I will add them to this list.

Additionally, the codebase has some inconsistencies, such as unclosed HTML tags. Contributors are encouraged to fix these minor bugs and make any improvements where possible.

Your efforts to enhance the reliability and usability of the ctrlpanel are greatly appreciated!

Thank you for your contributions!

### CODE REVIEW

**Review by AGuyNamedJens — COMMENTED** [review]
.env file for every ctrlpanel user must now contain the variables `DISCORD_CLIENT_ID` and `DISCORD_CLIENT_SECRET`, otherwise the method will not work on their computers. Add this to the documented breaking changes for the new version?

**Comment by jameskitt616** [comment]
> move the file [transferusers.php](https://github.com/Ctrlpanel-gg/panel/blob/development/transferusers.php) somewhere else then the root of the project..

attempted to fix this issue with #976

**Comment by S0ly** [comment]
guys anyone want to fix the remaining issues ?

**Comment by jameskitt616** [comment]
I opened a PR (#1002) for #989

**Pull request merged**
